

services:
  # MongoDB Database
  mongo:
    image: mongo:7
    container_name: softscape-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: softscape
    volumes:
      - mongo-data:/data/db
      - ./infra/docker/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - softscape-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: softscape-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass redis123
    volumes:
      - redis-data:/data
    networks:
      - softscape-network

  # API Backend
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
      target: development
    container_name: softscape-api
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGO_URI=mongodb://admin:admin123@mongo:27017/softscape?authSource=admin
      - REDIS_URL=redis://:redis123@redis:6379
      - JWT_SECRET=dev-jwt-secret-key
      - CORS_ORIGIN=http://localhost:3000,http://localhost:3002
    volumes:
      - ./apps/api:/app
      - /app/node_modules
      - ./apps/api/uploads:/app/uploads
      - ./apps/api/logs:/app/logs
    depends_on:
      - mongo
      - redis
    networks:
      - softscape-network

  # Web Frontend
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
      target: development
    container_name: softscape-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001/api/v1
    volumes:
      - ./apps/web:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - api
    networks:
      - softscape-network

  # Admin Dashboard
  admin:
    build:
      context: ./apps/admin
      dockerfile: Dockerfile
      target: development
    container_name: softscape-admin
    restart: unless-stopped
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001/api/v1
    volumes:
      - ./apps/admin:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - api
    networks:
      - softscape-network

volumes:
  mongo-data:
  redis-data:

networks:
  softscape-network:
    driver: bridge

