[build]
  # Build command
  command = "npm run build"
  
  # Directory with the deploy-ready files
  publish = "dist"
  
  # Functions directory (if using Netlify Functions)
  # functions = "netlify/functions"

[build.environment]
  # Node version
  NODE_VERSION = "18"
  
  # NPM version
  NPM_VERSION = "9"

# Redirect rules are in public/_redirects
# Header rules are in public/_headers

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-lighthouse"

# Deploy contexts
[context.production]
  command = "npm run build"
  publish = "dist"
  
[context.deploy-preview]
  command = "npm run build"
  publish = "dist"

[context.branch-deploy]
  command = "npm run build"
  publish = "dist"

# Dev server configuration
[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173
  autoLaunch = false
